export const CART_ADD_SERVICE = 'CART_ADD_SERVICE';
export const CART_REMOVE_SERVICE = 'CART_REMOVE_SERVICE';
export const CART_CHANGE_FIELD = 'CART_CHANGE_FIELD';
export const POST_ORDER_REQUEST = 'POST_ORDER_REQUEST';
export const POST_ORDER_FAILURE = 'POST_ORDER_FAILURE';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
