export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_CHANGE = 'CATEGORIES_CHANGE';
