export const ITEMS_LIST_REQUEST = 'ITEMS_LIST_REQUEST';
export const ITEMS_LIST_FAILURE = 'ITEMS_LIST_FAILURE';
export const ITEMS_LIST_SUCCESS = 'ITEMS_LIST_SUCCESS';
export const ITEMS_MORE_REQUEST = 'ITEMS_MORE_REQUEST';
export const ITEMS_MORE_FAILURE = 'ITEMS_MORE_FAILURE';
export const ITEMS_MORE_SUCCESS = 'ITEMS_MORE_SUCCESS';
